# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gols_time_casa', models.IntegerField(default=0)),
                ('gols_time_visitante', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gols_casa', models.IntegerField(default=0)),
                ('gols_visitante', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StatusPartida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descricao', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='jogador',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='partida',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.StatusPartida'),
        ),
        migrations.AddField(
            model_name='partida',
            name='time_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_casa', to='administracao.Time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='time_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_visitante', to='administracao.Time'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='id_partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.Partida'),
        ),
    ]
